apiVersion: v1 
kind: Service
metadata:
  name: events-ui-service
spec:
  ports:
  - name: http
    port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    app: demo-ui
    env: dev
  type: LoadBalancer
