apiVersion: apps/v1 
kind: Deployment
metadata:
  name: events-ui
spec: 
  selector:
    matchLabels:
      app: demo-ui
      env: dev
  replicas: 2 # tells deployment to run 1 pod matching the template
  template:
    metadata:
      labels:
        app: demo-ui
        env: dev
    spec:
      containers:
      - name: events-ui
        image: joshenderson/external:v1.0
        env: 
        - name: SERVER
          value: "http://events-api-service:8082"
        - name: SERVICE_PORT
          value: "8080"
        ports:
        - containerPort: 8080
            
        
