apiVersion: v1 
kind: Service
metadata:
  name: events-api-service
spec:
  ports:
  - name: http
    port: 8082
    targetPort: 8082
    protocol: TCP
  selector:
    app: events-api
  type: ClusterIP
